---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(lubridate)
library(lavaan)
library(psych)
library(psy)
library(biglm)
theme_set(theme_bw())

```

## Os dados

```{r}

desenvolvedores = read_csv(here::here("data/Base de bados para teste Teamwork Quality (respostas) - Respostas ao formulário 1.csv"))

desenvolvedores = desenvolvedores %>%
    rename(
        role = `Your Role`,
        experience_soft_dev = `Years of experience with software development`,
        experience_agile_dev = `Years of experience with agile development`,
        project_name = `Project Name`,
        communication1 = `1. There is frequent communication within the team.`,
        communication2 = `2. The team members communicate often in spontaneous meetings, phone conversations, etc.`,
        communication3 = `3. The team members communicate mostly directly and personally with each other`,
        communication4 = `4. There are mediators through whom much communication is conducted`,
        communication5 = `5. Relevant ideas and information relating to the teamwork is shared openly by all team members`,
        communication6 = `6. Important information is kept away from other team members in certain situations`,
        communication7 = `7. In the team there are conflicts regarding the openness of the information flow`,
        communication8 = `8. The team members are happy with the timeliness in which they receive information from other teammembers`,
        communication9 = `9. The team members are happy with the precision of the information they receive from other teammembers`,
        communication10 = `10. The team members are happy with the usefulness of the information they receive from other teammembers`,
        coordination1 = `11. The work done on subtasks within the team is closely harmonized`,
        coordination2 = `12. There are clear and fully comprehended goals for subtasks within our team`,
        coordination3 = `13. The goals for subtasks are accepted by all team members`,
        coordination4 = `14. There are conflicting interests in our team regarding subtasks/subgoals`,
        mutual_support1 = `15. The team members help and support each other as best they can`,
        mutual_support2 = `16. If conflicts come up, they are easily and quickly resolved`,
        mutual_support3 = `17. Discussions and controversies are conducted constructively`,
        mutual_support4 = `18. Suggestions and contributions of team members are respected`,
        mutual_support5 = `19. Suggestions and contributions of team members are discussed and further developed`,
        mutual_support6 = `20. The team is able to reach consensus regarding important issues`,
        mutual_support7 = `21. The team cooperate well`,
        effort1 = `22. Every team member fully pushes the teamwork`,
        effort2 = `23. Every team member makes the teamwork their highest priority`,
        effort3 = `24. The team put(s) much effort into the teamwork`,
        effort4 = `25. There are conflicts regarding the effort that team members put into the teamwork`,
        cohesion1 = `26. The teamwork is important to the team`,
        cohesion2 = `27. It is important to team members to be part of the team`,
        cohesion3 = `28. The team does not see anything special in this teamwork`,
        cohesion4 = `29. The team members are strongly attached to the team`,
        cohesion5 = `30. All team members are fully integrated in the team`,
        cohesion6 = `31. There were many personal conflicts in the team`,
        cohesion7 = `32. There is mutual sympathy between the members of the team`,
        cohesion8 = `33. The team sticks together`,
        cohesion9 = `34. The members of the team feel proud to be part of the team`,
        cohesion10 = `35. Every team member feels responsible for maintaining and protecting the team`,
        contribution1 = `36. The team recognizes the specific characteristics (strengths and weaknesses) of the individual teammembers`,
        contribution2 = `37. The team members contribute to the achievement of the team's goals in accordance with their specific potential`,
        contribution3 = `38. Imbalance of member contributions cause conflicts in our team`,
        work_satisfaction1 = `39. So far, the team can be pleased with its work`,
        work_satisfaction2 = `40. The team members gain from the collaborative teamwork`,
        work_satisfaction3 = `41. The team members will like to do this type of collaborative work again`,
        work_satisfaction4 = `42. We are able to acquire important know-how through this teamwork`,
        learning1 = `43. We consider this teamwork as a technical success`,
        learning2 = `44. The team learn important lessons from this teamwork`,
        learning3 = `45. Teamwork promotes one personally`,
        learning4 = `46. Teamwork promotes one professionally`,
        effectiveness1 = `47. Going by the results, this teamwork can be regarded as successful`,
        effectiveness2 = `48. All demands of the customers are satisfied`,
        effectiveness3 = `49. From the company's perspective, all team goals are achieved`,
        effectiveness4 = `50. The performance of the team advances our image to the customer`,
        effectiveness5 = `51. The teamwork result is of high quality`,
        effectiveness6 = `52. The customer is satisfied with the quality of the teamwork result`,
        effectiveness7 = `53. The team is satisfied with the teamwork result`,
        effectiveness8 = `54. The product produced in the team, requires little rework`,
        effectiveness9 = `55. The product proves to be stable in operation`,
        effectiveness10 = `56. The product proves to be robust in operation`,
        efficiency1 = `57. The company is satisfied with how the teamwork progresses`,
        efficiency2 = `58. Overall, the team works in a cost-efficient way`,
        efficiency3 = `59. Overall, the team works in a time-efficient way`,
        efficiency4 = `60. The team is within schedule`,
        efficiency5 = `61. The team is within budget`

        
    )
```


```{r}

desenvolvedores %>%
    summarise(media_idade = mean(Age), desvio_idade = sd(Age), mediana_idade = median(Age),
              media_experience_soft_dev = mean(experience_soft_dev), 
              desvio_experience_soft_dev = sd(experience_soft_dev),
              mediana_experience_soft_dev = median(experience_soft_dev),
              media_experience_agile_dev = mean(experience_agile_dev), 
              desvio_experience_agile_dev = sd(experience_agile_dev),
              mediana_experience_agile_dev = median(experience_agile_dev))
  

desenvolvedores = desenvolvedores %>%
  mutate(communication = (communication1 + communication2 + communication3 + communication4 + communication5 + communication6 +
                                 communication7 + communication8 + communication9 + communication10)/10,
                          coordination = (coordination1 + coordination2 + coordination3 + coordination4)/4,
                          mutual_support = (mutual_support1 + mutual_support2 + mutual_support3 + mutual_support4 + mutual_support5 +            mutual_support6 + mutual_support7)/7,
                          effort = (effort1 + effort2 + effort3 + effort4)/4,
                          cohesion = (cohesion1 + cohesion2 +  cohesion3 + cohesion4 + cohesion5 + cohesion6 + cohesion7 + cohesion8 + cohesion9 + cohesion10)/10,
                          contribution = (contribution1 + contribution2 + contribution3)/3,
                          work_satisfaction = (work_satisfaction1 + work_satisfaction2 + work_satisfaction3 + work_satisfaction4)/4,
                          learning = (learning1 + learning2 + learning3 + learning4)/4,
                          effectiveness = (effectiveness1 + effectiveness2 + effectiveness3 + effectiveness4 + effectiveness5 + effectiveness6 + effectiveness7 + effectiveness8 + effectiveness9 + effectiveness10)/10,
                          efficiency = (efficiency1 + efficiency2 + efficiency3 + efficiency4 + efficiency5)/5)
         


```

```{r}

means = desenvolvedores %>%
  group_by(project_name)%>%
  summarise(communication_mean = mean(communication), 
            coordination_mean = mean(coordination), 
            mutual_support_mean = mean(mutual_support),
            effort_mean = mean(effort), 
            cohesion_mean = mean(cohesion), 
            contribution_mean = mean(contribution),
            work_satisfaction_mean = mean(work_satisfaction), 
            learning_mean = mean(learning), 
            effectiveness_mean_team = mean(effectiveness),
            efficiency_mean_team = mean(efficiency),
            effectiveness_mean_TL = mean(effectiveness[role == 'Technical Lead']),
            efficiency_mean_TL = mean(efficiency[role == 'Technical Lead']),
            effectiveness_mean_M = mean(effectiveness[role == 'Manager']),
            efficiency_mean_M = mean(efficiency[role == 'Manager']))
means

```

#Teste Alpha de Cronbach

```{r}
alfa <- alpha(means, check.keys=TRUE)

alfa



```

#SEM


```{r}

model <- '  #model
            teamWork =~ communication_mean +
                        coordination_mean + 
                        mutual_support_mean + 
                        effort_mean + 
                        cohesion_mean + 
                        contribution_mean
            performance_team =~ effectiveness_mean_team + efficiency_mean_team
            performance_TL =~ effectiveness_mean_TL + efficiency_mean_TL
            performance_M =~ effectiveness_mean_M + efficiency_mean_M
            personal_sucess =~ work_satisfaction_mean + learning_mean
              
            #regressão
            personal_sucess ~ teamWork
            performance_team ~ teamWork
            performance_TL ~ teamWork
            performance_M ~teamWork
            
            # residual correlations
            communication_mean ~~ coordination_mean
            communication_mean ~~ mutual_support_mean
            communication_mean ~~ effort_mean
            communication_mean ~~ cohesion_mean
            communication_mean ~~ contribution_mean
            communication_mean ~~ effectiveness_mean_team
            communication_mean ~~ efficiency_mean_team
            communication_mean ~~ effectiveness_mean_TL
            communication_mean ~~ efficiency_mean_TL
            communication_mean ~~ effectiveness_mean_M
            communication_mean ~~ efficiency_mean_M
            communication_mean ~~ work_satisfaction_mean
            communication_mean ~~ learning_mean
            coordination_mean  ~~ mutual_support_mean
            coordination_mean  ~~ effort_mean
            coordination_mean  ~~ cohesion_mean
            coordination_mean  ~~ contribution_mean
            coordination_mean  ~~ effectiveness_mean_team
            coordination_mean  ~~ efficiency_mean_team
            coordination_mean  ~~ effectiveness_mean_TL
            coordination_mean  ~~ efficiency_mean_TL
            coordination_mean  ~~ effectiveness_mean_M
            coordination_mean  ~~ efficiency_mean_M
            coordination_mean  ~~ work_satisfaction_mean
            coordination_mean  ~~ learning_mean
            mutual_support_mean ~~ effort_mean
            mutual_support_mean ~~ cohesion_mean
            mutual_support_mean ~~ contribution_mean 
            mutual_support_mean ~~ effectiveness_mean_team
            mutual_support_mean ~~ efficiency_mean_team
            mutual_support_mean ~~ effectiveness_mean_TL
            mutual_support_mean ~~ efficiency_mean_TL
            mutual_support_mean ~~ effectiveness_mean_M
            mutual_support_mean ~~ efficiency_mean_M 
            mutual_support_mean ~~ work_satisfaction_mean
            mutual_support_mean ~~ learning_mean
            effort_mean ~~ cohesion_mean
            effort_mean ~~ contribution_mean
            effort_mean ~~ effectiveness_mean_team
            effort_mean ~~ efficiency_mean_team
            effort_mean ~~ effectiveness_mean_TL
            effort_mean ~~ efficiency_mean_TL
            effort_mean ~~ effectiveness_mean_M
            effort_mean ~~ efficiency_mean_M
            effort_mean ~~ work_satisfaction_mean
            effort_mean ~~ learning_mean
            cohesion_mean ~~ contribution_mean
            cohesion_mean ~~ effectiveness_mean_team
            cohesion_mean ~~ efficiency_mean_team
            cohesion_mean ~~ effectiveness_mean_TL
            cohesion_mean ~~ efficiency_mean_TL
            cohesion_mean ~~ effectiveness_mean_M
            cohesion_mean ~~ efficiency_mean_M
            cohesion_mean ~~ work_satisfaction_mean
            cohesion_mean ~~ learning_mean
            contribution_mean ~~ effectiveness_mean_team
            contribution_mean ~~ efficiency_mean_team
            contribution_mean ~~ effectiveness_mean_TL
            contribution_mean ~~ efficiency_mean_TL
            contribution_mean ~~ effectiveness_mean_M
            contribution_mean ~~ efficiency_mean_M
            contribution_mean ~~ work_satisfaction_mean
            contribution_mean ~~ learning_mean
            work_satisfaction_mean ~~ learning_mean
            work_satisfaction_mean ~~ effectiveness_mean_team
            work_satisfaction_mean ~~ efficiency_mean_team
            work_satisfaction_mean ~~ effectiveness_mean_TL
            work_satisfaction_mean ~~ efficiency_mean_TL
            work_satisfaction_mean ~~ effectiveness_mean_M
            work_satisfaction_mean ~~ efficiency_mean_M
            learning_mean ~~ effectiveness_mean_team
            learning_mean ~~ efficiency_mean_team
            learning_mean ~~ effectiveness_mean_TL
            learning_mean ~~ efficiency_mean_TL
            learning_mean ~~ effectiveness_mean_M
            learning_mean ~~ efficiency_mean_M
            effectiveness_mean_team ~~ efficiency_mean_team
            effectiveness_mean_team ~~ effectiveness_mean_TL
            effectiveness_mean_team ~~ efficiency_mean_TL
            effectiveness_mean_team ~~ effectiveness_mean_M 
            effectiveness_mean_team ~~ efficiency_mean_M 
            efficiency_mean_team ~~ effectiveness_mean_TL
            efficiency_mean_team ~~ efficiency_mean_TL
            efficiency_mean_team ~~ effectiveness_mean_M
            efficiency_mean_team ~~ efficiency_mean_M
            effectiveness_mean_TL ~~ efficiency_mean_TL
            effectiveness_mean_TL ~~ effectiveness_mean_M
            effectiveness_mean_TL ~~ efficiency_mean_M
            efficiency_mean_TL ~~ effectiveness_mean_M
            efficiency_mean_TL ~~ efficiency_mean_M
            effectiveness_mean_M ~~ efficiency_mean_M
              
'
                         

#fit <- sem(model = model, data = means, verbose = TRUE, optim.method = "em")
#summary(fit, standardized=TRUE)

fit <- sem(model, data=means[1:21, ])
summary(fit, standardized=TRUE)

```

```{r}

model2 <- '
  # measurement model
    ind60 =~ x1 + x2 + x3
    dem60 =~ y1 + y2 + y3 + y4
    dem65 =~ y5 + y6 + y7 + y8
  # regressions
    dem60 ~ ind60
    dem65 ~ ind60 + dem60
  # residual correlations
    y1 ~~ y5
    y2 ~~ y4 + y6
    y3 ~~ y7
    y4 ~~ y8
    y6 ~~ y8
'
fit <- sem(model2, data=PoliticalDemocracy[1:23, ])
summary(fit, standardized=TRUE)

```